---
- name: Install Zabbix and Postgre Server
  hosts: local
  become: yes

  vars:
    zabbix_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31376632353838643634343533636336633365353030323264316464376263333339653035666534
          6333396533623162333231346464363830323235346431630a306638396662636265383939393838
          63666233393763333933616363663732333833303164343466313333386166666465343266303136
          6534646564313465390a393666663535323066633335373333386439663961343638626133623637
          3232

  tasks:
    - block: #=====================RedHat=======================#
      - name: Install Postgre
        yum: name=postgresql-server update_cache=yes

      - name: New claster
        shell: sudo postgresql-setup --initdb

      - name: Start Postgre
        service: name=postgresql state=started enabled=yes

      - name: Prepare for Zabbix
        shell: |
          sudo -u postgres createuser --pwprompt zabbix
          sudo -u postgres createdb -O zabbix zabbix
          rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm
          dnf module switch-to php:7.4

      - name: Install Zabbix
        yum:
          name:
            - zabbix-server-pgsql
            - zabbix-web-pgsql
            - zabbix-apache-conf
            - zabbix-sql-scripts
            - zabbix-selinux-policy
            - zabbix-agent
          update_cache: yes

      - name: Update Zabbix Pass
        shell: |
          sudo sed -i 's/DBPassword/#DBPassword/' /etc/zabbix/zabbix_server.conf
          sudo echo 'DBPassword={{ zabbix_pass }}' >> /etc/zabbix/zabbix_server.conf

      - name: Start Zabbix
        service:
          name: '{{ item }}'
          state: restarted
          enabled: yes
        with_items:
          - zabbix-server
          - zabbix-agent
          - httpd
          - php-fpm

      when: ansible_os_family == "RedHat"
